In [1]:
!uv pip install lxml html5lib pandas matplotlib numpy scikit-learn

Audited 6 packages in 54ms

In [2]:
!uv pip install ipykernel
!python -m ipykernel install --user --name=MiniProject --display-name "Python (MiniProject)"

Audited 1 package in 9ms
Installed kernelspec MiniProject in /home/afrozdebian/.local/share/jupyter/kernels/miniproject

In [3]:
!uv pip freeze>requirements.txt

In [13]:
import pandas as pd

In [14]:
df = pd.read_html("horizontal_crop_vertical_year_report_maharashtra.xls", flavor="lxml")[0]
df.head()

            State        District         Year      Arhar/Tur  \
            State        District         Year         Kharif
            State        District         Year Area (Hectare)
0  1. Maharashtra  1. Ahilyanagar  1997 - 1998        17600.0
1  1. Maharashtra  1. Ahilyanagar  1998 - 1999        18800.0
2  1. Maharashtra  1. Ahilyanagar  1999 - 2000        19000.0
3  1. Maharashtra  1. Ahilyanagar  2000 - 2001        19100.0
4  1. Maharashtra  1. Ahilyanagar  2001 - 2002        16700.0

                                                     Bajra  \
                                                    Kharif
  Production (Tonnes) Yield (Tonne/Hectare) Area (Hectare)
0              6300.0                  0.36       274100.0
1              9700.0                  0.52       302400.0
2              9900.0                  0.52       310600.0
3              9400.0                  0.49       326100.0
4              5400.0                  0.32       194400.0

                                                            ...  \
                                                    Summer  ...
  Production (Tonnes) Yield (Tonne/Hectare) Area (Hectare)  ...
0            152800.0                  0.56            NaN  ...
1            243900.0                  0.81            NaN  ...
2            178300.0                  0.57            NaN  ...
3            187300.0                  0.57            NaN  ...
4             82000.0                  0.42            NaN  ...

         other oilseeds                                     \
                 Kharif           Rabi
  Yield (Tonne/Hectare) Area (Hectare) Production (Tonnes)
0                   NaN            NaN                 NaN
1                   NaN            NaN                 NaN
2                   NaN            NaN                 NaN
3                   NaN            NaN                 NaN
4                   NaN            NaN                 NaN

                                                            \
                                Summer
  Yield (Tonne/Hectare) Area (Hectare) Production (Tonnes)
0                   NaN            NaN                 NaN
1                   NaN            NaN                 NaN
2                   NaN            NaN                 NaN
3                   NaN            NaN                 NaN
4                   NaN            NaN                 NaN

                        Other Summer Pulses                      \
                                     Summer
  Yield (Tonne/Hectare)      Area (Hectare) Production (Tonnes)
0                   NaN                 NaN                 NaN
1                   NaN                 NaN                 NaN
2                   NaN                 NaN                 NaN
3                   NaN                 NaN                 NaN
4                   NaN                 NaN                 NaN



  Yield (Tonne/Hectare)
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN

[5 rows x 156 columns]

In [15]:
df.columns

MultiIndex([(              'State',    'State',                 'State'),
            (           'District', 'District',              'District'),
            (               'Year',     'Year',                  'Year'),
            (          'Arhar/Tur',   'Kharif',        'Area (Hectare)'),
            (          'Arhar/Tur',   'Kharif',   'Production (Tonnes)'),
            (          'Arhar/Tur',   'Kharif', 'Yield (Tonne/Hectare)'),
            (              'Bajra',   'Kharif',        'Area (Hectare)'),
            (              'Bajra',   'Kharif',   'Production (Tonnes)'),
            (              'Bajra',   'Kharif', 'Yield (Tonne/Hectare)'),
            (              'Bajra',   'Summer',        'Area (Hectare)'),
            ...
            (     'other oilseeds',   'Kharif', 'Yield (Tonne/Hectare)'),
            (     'other oilseeds',     'Rabi',        'Area (Hectare)'),
            (     'other oilseeds',     'Rabi',   'Production (Tonnes)'),
            (     'other oilseeds',     'Rabi', 'Yield (Tonne/Hectare)'),
            (     'other oilseeds',   'Summer',        'Area (Hectare)'),
            (     'other oilseeds',   'Summer',   'Production (Tonnes)'),
            (     'other oilseeds',   'Summer', 'Yield (Tonne/Hectare)'),
            ('Other Summer Pulses',   'Summer',        'Area (Hectare)'),
            ('Other Summer Pulses',   'Summer',   'Production (Tonnes)'),
            ('Other Summer Pulses',   'Summer', 'Yield (Tonne/Hectare)')],
           length=156)

In [16]:
df.columns = ['_'.join(col).strip() for col in df.columns]

In [17]:
df.head()

,State_State_State,District_District_District,Year_Year_Year,Arhar/Tur_Kharif_Area (Hectare),Arhar/Tur_Kharif_Production (Tonnes),Arhar/Tur_Kharif_Yield (Tonne/Hectare),Bajra_Kharif_Area (Hectare),Bajra_Kharif_Production (Tonnes),Bajra_Kharif_Yield (Tonne/Hectare),Bajra_Summer_Area (Hectare),...,other oilseeds_Kharif_Yield (Tonne/Hectare),other oilseeds_Rabi_Area (Hectare),other oilseeds_Rabi_Production (Tonnes),other oilseeds_Rabi_Yield (Tonne/Hectare),other oilseeds_Summer_Area (Hectare),other oilseeds_Summer_Production (Tonnes),other oilseeds_Summer_Yield (Tonne/Hectare),Other Summer Pulses_Summer_Area (Hectare),Other Summer Pulses_Summer_Production (Tonnes),Other Summer Pulses_Summer_Yield (Tonne/Hectare)
0,1. Maharashtra,1. Ahilyanagar,1997 - 1998,17600.0,6300.0,0.36,274100.0,152800.0,0.56,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1. Maharashtra,1. Ahilyanagar,1998 - 1999,18800.0,9700.0,0.52,302400.0,243900.0,0.81,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1. Maharashtra,1. Ahilyanagar,1999 - 2000,19000.0,9900.0,0.52,310600.0,178300.0,0.57,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1. Maharashtra,1. Ahilyanagar,2000 - 2001,19100.0,9400.0,0.49,326100.0,187300.0,0.57,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1. Maharashtra,1. Ahilyanagar,2001 - 2002,16700.0,5400.0,0.32,194400.0,82000.0,0.42,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
id_cols = ["State_State_State", "District_District_District", "Year_Year_Year"]

In [19]:
df_long = df.melt(
    id_vars=id_cols,
    var_name="variable",
    value_name="value"
)

In [20]:
df_long.head()

,State_State_State,District_District_District,Year_Year_Year,variable,value
0,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Arhar/Tur_Kharif_Area (Hectare),17600.0
1,1. Maharashtra,1. Ahilyanagar,1998 - 1999,Arhar/Tur_Kharif_Area (Hectare),18800.0
2,1. Maharashtra,1. Ahilyanagar,1999 - 2000,Arhar/Tur_Kharif_Area (Hectare),19000.0
3,1. Maharashtra,1. Ahilyanagar,2000 - 2001,Arhar/Tur_Kharif_Area (Hectare),19100.0
4,1. Maharashtra,1. Ahilyanagar,2001 - 2002,Arhar/Tur_Kharif_Area (Hectare),16700.0

In [21]:
df_long[["crop", "season", "metric"]] = df_long["variable"].str.split("_", n=2, expand=True)

In [22]:
df_long.head()

,State_State_State,District_District_District,Year_Year_Year,variable,value,crop,season,metric
0,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Arhar/Tur_Kharif_Area (Hectare),17600.0,Arhar/Tur,Kharif,Area (Hectare)
1,1. Maharashtra,1. Ahilyanagar,1998 - 1999,Arhar/Tur_Kharif_Area (Hectare),18800.0,Arhar/Tur,Kharif,Area (Hectare)
2,1. Maharashtra,1. Ahilyanagar,1999 - 2000,Arhar/Tur_Kharif_Area (Hectare),19000.0,Arhar/Tur,Kharif,Area (Hectare)
3,1. Maharashtra,1. Ahilyanagar,2000 - 2001,Arhar/Tur_Kharif_Area (Hectare),19100.0,Arhar/Tur,Kharif,Area (Hectare)
4,1. Maharashtra,1. Ahilyanagar,2001 - 2002,Arhar/Tur_Kharif_Area (Hectare),16700.0,Arhar/Tur,Kharif,Area (Hectare)

In [23]:
df_final = df_long.pivot_table(
    index=id_cols + ["crop", "season"],
    columns="metric",
    values="value"
).reset_index()

In [24]:
df_final.head()

metric,State_State_State,District_District_District,Year_Year_Year,crop,season,Area (Hectare),Production (Bales),Production (Tonnes),Yield (Bales/Hectare),Yield (Tonne/Hectare)
0,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Arhar/Tur,Kharif,17600.0,NaN,6300.0,NaN,0.36
1,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Bajra,Kharif,274100.0,NaN,152800.0,NaN,0.56
2,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Gram,Kharif,40800.0,NaN,18600.0,NaN,0.46
3,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Jowar,Kharif,900.0,NaN,1100.0,NaN,1.22
4,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Jowar,Rabi,598400.0,NaN,217000.0,NaN,0.36

In [25]:
df_final.columns.name = None
df_final.rename(columns={
    "State_State_State": "state",
    "District_District_District": "district",
    "Year_Year_Year": "year"
}, inplace=True)

In [26]:
df_final.head()

,state,district,year,crop,season,Area (Hectare),Production (Bales),Production (Tonnes),Yield (Bales/Hectare),Yield (Tonne/Hectare)
0,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Arhar/Tur,Kharif,17600.0,NaN,6300.0,NaN,0.36
1,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Bajra,Kharif,274100.0,NaN,152800.0,NaN,0.56
2,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Gram,Kharif,40800.0,NaN,18600.0,NaN,0.46
3,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Jowar,Kharif,900.0,NaN,1100.0,NaN,1.22
4,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Jowar,Rabi,598400.0,NaN,217000.0,NaN,0.36

In [27]:
df_final.columns

Index(['state', 'district', 'year', 'crop', 'season', 'Area (Hectare)',
       'Production (Bales)', 'Production (Tonnes)', 'Yield (Bales/Hectare)',
       'Yield (Tonne/Hectare)'],
      dtype='object')

In [28]:
DATASET_INFO = {
    "state": "Maharashtra"
}

In [29]:
df = df.copy()

In [30]:
df = df_final.drop(columns=["state"])
df = df.copy()   # ✅ fixes warning

df["production"] = df["Production (Tonnes)"].fillna(df["Production (Bales)"])
df["yield"] = df["Yield (Tonne/Hectare)"].fillna(df["Yield (Bales/Hectare)"])

In [31]:
df.head()

,district,year,crop,season,Area (Hectare),Production (Bales),Production (Tonnes),Yield (Bales/Hectare),Yield (Tonne/Hectare),production,yield
0,1. Ahilyanagar,1997 - 1998,Arhar/Tur,Kharif,17600.0,NaN,6300.0,NaN,0.36,6300.0,0.36
1,1. Ahilyanagar,1997 - 1998,Bajra,Kharif,274100.0,NaN,152800.0,NaN,0.56,152800.0,0.56
2,1. Ahilyanagar,1997 - 1998,Gram,Kharif,40800.0,NaN,18600.0,NaN,0.46,18600.0,0.46
3,1. Ahilyanagar,1997 - 1998,Jowar,Kharif,900.0,NaN,1100.0,NaN,1.22,1100.0,1.22
4,1. Ahilyanagar,1997 - 1998,Jowar,Rabi,598400.0,NaN,217000.0,NaN,0.36,217000.0,0.36

In [32]:
df.columns

Index(['district', 'year', 'crop', 'season', 'Area (Hectare)',
       'Production (Bales)', 'Production (Tonnes)', 'Yield (Bales/Hectare)',
       'Yield (Tonne/Hectare)', 'production', 'yield'],
      dtype='object')

In [33]:
df = df.drop(
    columns = [
        "Production (Tonnes)",
    "Production (Bales)",
    "Yield (Tonne/Hectare)",
    "Yield (Bales/Hectare)"
    ], errors = "ignore"
)

In [34]:
df.columns

Index(['district', 'year', 'crop', 'season', 'Area (Hectare)', 'production',
       'yield'],
      dtype='object')

In [35]:
df=df.rename(
    columns={
        "Area (Hectare)":"area"
    }
)

In [36]:
df.columns

Index(['district', 'year', 'crop', 'season', 'area', 'production', 'yield'], dtype='object')

In [37]:
df=df.drop(
    columns="production"
)

In [38]:
df.columns

Index(['district', 'year', 'crop', 'season', 'area', 'yield'], dtype='object')

In [39]:
df_encoded=pd.get_dummies(df, columns=["district", "crop", "season"])

In [40]:
df_encoded.head(3)

,year,area,yield,district_1. Ahilyanagar,district_10. Dhule,district_11. Gadchiroli,district_12. Gondia,district_13. Hingoli,district_14. Jalgaon,district_15. Jalna,...,crop_Sugarcane,crop_Sunflower,crop_Total foodgrain,crop_Urad,crop_Wheat,crop_other oilseeds,season_Autumn,season_Kharif,season_Rabi,season_Summer
0,1997 - 1998,17600.0,0.36,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,1997 - 1998,274100.0,0.56,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,1997 - 1998,40800.0,0.46,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [41]:
df_encoded.to_csv("Encoded_dataset.csv", index=False)

In [34]:
df_encoded.columns

Index(['year', 'area', 'yield', 'district_1. Ahilyanagar',
       'district_10. Dhule', 'district_11. Gadchiroli', 'district_12. Gondia',
       'district_13. Hingoli', 'district_14. Jalgaon', 'district_15. Jalna',
       'district_16. Kolhapur', 'district_17. Latur', 'district_18. Mumbai',
       'district_19. Mumbai suburban', 'district_2. Akola',
       'district_20. Nagpur', 'district_21. Nanded', 'district_22. Nandurbar',
       'district_23. Nashik', 'district_24. Palghar', 'district_25. Parbhani',
       'district_26. Pune', 'district_27. Raigad', 'district_28. Ratnagiri',
       'district_29. Sangli', 'district_3. Amravati', 'district_30. Satara',
       'district_31. Sindhudurg', 'district_32. Solapur', 'district_33. Thane',
       'district_34. Wardha', 'district_35. Washim', 'district_36. Yavatmal',
       'district_4. Beed', 'district_5. Bhandara', 'district_6. Buldhana',
       'district_7. Chandrapur', 'district_8. Chhatrapati Sambhajinagar',
       'district_9. Dharashiv', 'crop_Arhar/Tur', 'crop_Bajra',
       'crop_Castor seed', 'crop_Cotton(lint)', 'crop_Gram', 'crop_Groundnut',
       'crop_Jowar', 'crop_Linseed', 'crop_Maize', 'crop_Moong(Green Gram)',
       'crop_Niger seed', 'crop_Other Cereals', 'crop_Other Kharif pulses',
       'crop_Other Rabi pulses', 'crop_Other Summer Pulses',
       'crop_Pulses total', 'crop_Ragi', 'crop_Rapeseed &Mustard', 'crop_Rice',
       'crop_Safflower', 'crop_Sesamum', 'crop_Small millets', 'crop_Soyabean',
       'crop_Sugarcane', 'crop_Sunflower', 'crop_Total foodgrain', 'crop_Urad',
       'crop_Wheat', 'crop_other oilseeds', 'season_Autumn', 'season_Kharif',
       'season_Rabi', 'season_Summer'],
      dtype='str')

In [35]:
df_encoded.size

1451376

In [36]:
df["crop"].value_counts().min

<bound method Series.min of crop
Maize                  1835
Groundnut              1412
Jowar                  1388
Sunflower              1363
Sesamum                1141
Rice                    990
Moong(Green Gram)       885
Urad                    870
Arhar/Tur               832
Gram                    807
Small millets           784
Wheat                   770
Other Kharif pulses     760
Soyabean                758
Other Rabi pulses       690
Cotton(lint)            654
Bajra                   582
Other Cereals           527
Safflower               487
Niger seed              481
Rapeseed &Mustard       473
Castor seed             422
Linseed                 389
other oilseeds          338
Ragi                    316
Other Summer Pulses     117
Pulses total             29
Sugarcane                29
Total foodgrain          29
Name: count, dtype: int64>

In [37]:
df_encoded["year"] = df_encoded["year"].str.split(" - ").str[0].astype(int)
df_encoded["year"].dtype

dtype('int64')

In [38]:
X=df_encoded.drop(columns=["yield"])
y=df_encoded["yield"]

In [39]:
X.columns

Index(['year', 'area', 'district_1. Ahilyanagar', 'district_10. Dhule',
       'district_11. Gadchiroli', 'district_12. Gondia',
       'district_13. Hingoli', 'district_14. Jalgaon', 'district_15. Jalna',
       'district_16. Kolhapur', 'district_17. Latur', 'district_18. Mumbai',
       'district_19. Mumbai suburban', 'district_2. Akola',
       'district_20. Nagpur', 'district_21. Nanded', 'district_22. Nandurbar',
       'district_23. Nashik', 'district_24. Palghar', 'district_25. Parbhani',
       'district_26. Pune', 'district_27. Raigad', 'district_28. Ratnagiri',
       'district_29. Sangli', 'district_3. Amravati', 'district_30. Satara',
       'district_31. Sindhudurg', 'district_32. Solapur', 'district_33. Thane',
       'district_34. Wardha', 'district_35. Washim', 'district_36. Yavatmal',
       'district_4. Beed', 'district_5. Bhandara', 'district_6. Buldhana',
       'district_7. Chandrapur', 'district_8. Chhatrapati Sambhajinagar',
       'district_9. Dharashiv', 'crop_Arhar/Tur', 'crop_Bajra',
       'crop_Castor seed', 'crop_Cotton(lint)', 'crop_Gram', 'crop_Groundnut',
       'crop_Jowar', 'crop_Linseed', 'crop_Maize', 'crop_Moong(Green Gram)',
       'crop_Niger seed', 'crop_Other Cereals', 'crop_Other Kharif pulses',
       'crop_Other Rabi pulses', 'crop_Other Summer Pulses',
       'crop_Pulses total', 'crop_Ragi', 'crop_Rapeseed &Mustard', 'crop_Rice',
       'crop_Safflower', 'crop_Sesamum', 'crop_Small millets', 'crop_Soyabean',
       'crop_Sugarcane', 'crop_Sunflower', 'crop_Total foodgrain', 'crop_Urad',
       'crop_Wheat', 'crop_other oilseeds', 'season_Autumn', 'season_Kharif',
       'season_Rabi', 'season_Summer'],
      dtype='str')

In [40]:
X["year"]

0        1997
1        1997
2        1997
3        1997
4        1997
         ...
20153    2022
20154    2022
20155    2022
20156    2022
20157    2022
Name: year, Length: 20158, dtype: int64

In [41]:
y

0        0.36
1        0.56
2        0.46
3        1.22
4        0.36
         ...
20153    0.53
20154    1.55
20155    0.34
20156    0.33
20157    0.44
Name: yield, Length: 20158, dtype: float64

In [42]:
X = X.drop(columns=["production"], errors="ignore")

In [43]:
X.columns

Index(['year', 'area', 'district_1. Ahilyanagar', 'district_10. Dhule',
       'district_11. Gadchiroli', 'district_12. Gondia',
       'district_13. Hingoli', 'district_14. Jalgaon', 'district_15. Jalna',
       'district_16. Kolhapur', 'district_17. Latur', 'district_18. Mumbai',
       'district_19. Mumbai suburban', 'district_2. Akola',
       'district_20. Nagpur', 'district_21. Nanded', 'district_22. Nandurbar',
       'district_23. Nashik', 'district_24. Palghar', 'district_25. Parbhani',
       'district_26. Pune', 'district_27. Raigad', 'district_28. Ratnagiri',
       'district_29. Sangli', 'district_3. Amravati', 'district_30. Satara',
       'district_31. Sindhudurg', 'district_32. Solapur', 'district_33. Thane',
       'district_34. Wardha', 'district_35. Washim', 'district_36. Yavatmal',
       'district_4. Beed', 'district_5. Bhandara', 'district_6. Buldhana',
       'district_7. Chandrapur', 'district_8. Chhatrapati Sambhajinagar',
       'district_9. Dharashiv', 'crop_Arhar/Tur', 'crop_Bajra',
       'crop_Castor seed', 'crop_Cotton(lint)', 'crop_Gram', 'crop_Groundnut',
       'crop_Jowar', 'crop_Linseed', 'crop_Maize', 'crop_Moong(Green Gram)',
       'crop_Niger seed', 'crop_Other Cereals', 'crop_Other Kharif pulses',
       'crop_Other Rabi pulses', 'crop_Other Summer Pulses',
       'crop_Pulses total', 'crop_Ragi', 'crop_Rapeseed &Mustard', 'crop_Rice',
       'crop_Safflower', 'crop_Sesamum', 'crop_Small millets', 'crop_Soyabean',
       'crop_Sugarcane', 'crop_Sunflower', 'crop_Total foodgrain', 'crop_Urad',
       'crop_Wheat', 'crop_other oilseeds', 'season_Autumn', 'season_Kharif',
       'season_Rabi', 'season_Summer'],
      dtype='str')

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [45]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators = 100, random_state=42)
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [46]:
y_pred = rf.predict(X_test)

In [47]:
from sklearn.metrics import r2_score, mean_squared_error
r2=r2_score(y_test, y_pred)
mse=mean_squared_error(y_test, y_pred)
print(f"R2:{r2}")
print(f"MSE:{mse}")

R2:0.8634683275549486
MSE:180.15526357925862

In [48]:
df_encoded["yield"].describe()

count    20158.000000
mean         1.331565
std         20.770522
min          0.000000
25%          0.360000
50%          0.630000
75%          1.100000
max       1494.000000
Name: yield, dtype: float64

In [49]:
df.groupby("crop")["yield"].describe()

,count,mean,std,min,25%,50%,75%,max
crop,,,,,,,,
Arhar/Tur,832.0,0.678846,0.378419,0.00,0.4300,0.620,0.8500,3.70
Bajra,582.0,0.660876,0.320806,0.00,0.4400,0.610,0.8875,1.68
Castor seed,422.0,0.315047,0.274177,0.00,0.1700,0.260,0.4000,3.00
Cotton(lint),654.0,1.592951,1.484563,0.15,0.9700,1.440,1.9900,34.14
Gram,807.0,0.747559,0.289614,0.00,0.5500,0.700,0.9000,2.86
Groundnut,1412.0,1.164561,0.598453,0.00,0.7600,1.000,1.4800,5.91
Jowar,1388.0,0.924971,0.589168,0.00,0.5700,0.830,1.1900,14.57
Linseed,389.0,0.309846,0.191352,0.00,0.2000,0.270,0.3500,1.00
Maize,1835.0,5.566458,67.203013,0.00,1.0650,1.680,2.3600,1494.00
Moong(Green Gram),885.0,0.466079,0.259768,0.00,0.2700,0.460,0.6200,2.54
Niger seed,481.0,0.260728,0.193613,0.00,0.1500,0.240,0.3300,1.00
Other Cereals,527.0,0.566433,0.379489,0.00,0.3000,0.480,0.7450,3.33
Other Kharif pulses,760.0,0.377145,0.208525,0.00,0.2500,0.340,0.4700,2.00
Other Rabi pulses,690.0,0.447435,0.244480,0.00,0.3300,0.430,0.5300,3.60
Other Summer Pulses,117.0,0.446838,0.245166,0.00,0.3000,0.380,0.5400,1.28
Pulses total,29.0,0.352414,0.162297,0.07,0.2100,0.350,0.4600,0.73
Ragi,316.0,1.044873,0.357604,0.00,0.7900,1.000,1.2350,2.37
Rapeseed &Mustard,473.0,0.348076,0.258618,0.00,0.2000,0.320,0.5000,1.76
Rice,990.0,1.858626,7.121757,0.00,0.7425,1.625,2.4100,223.73
Safflower,487.0,0.559589,0.272397,0.00,0.3950,0.530,0.6850,2.15
Sesamum,1141.0,0.780570,11.498301,0.00,0.1900,0.250,0.3400,275.00
Small millets,784.0,0.537411,0.342734,0.00,0.3300,0.500,0.6700,2.37
Soyabean,758.0,1.237810,0.550463,0.14,0.8225,1.220,1.5675,3.88
Sugarcane,29.0,67.238966,38.359728,0.80,66.8200,82.070,88.4100,132.94
Sunflower,1363.0,0.613280,0.319699,0.00,0.4200,0.540,0.7500,3.00
Total foodgrain,29.0,0.987586,0.547812,0.33,0.5900,0.850,1.0900,2.43
Urad,870.0,0.522736,0.234746,0.00,0.3500,0.510,0.6700,1.16
Wheat,770.0,1.432221,0.512995,0.21,1.0725,1.400,1.7775,2.91
other oilseeds,338.0,0.376095,0.482019,0.00,0.2000,0.290,0.4400,6.00

In [50]:
# Since dataset of all crops is merged together the model is kind of inaccurate
# It is statistically superior but scientifically inaccurate
# Hence we now train the model for each crop separately and see the results as their yields differ greatly depending upon their bioavailability

In [51]:
df

             district         year            crop  season       area  yield
0      1. Ahilyanagar  1997 - 1998       Arhar/Tur  Kharif   17600.00   0.36
1      1. Ahilyanagar  1997 - 1998           Bajra  Kharif  274100.00   0.56
2      1. Ahilyanagar  1997 - 1998            Gram  Kharif   40800.00   0.46
3      1. Ahilyanagar  1997 - 1998           Jowar  Kharif     900.00   1.22
4      1. Ahilyanagar  1997 - 1998           Jowar    Rabi  598400.00   0.36
...               ...          ...             ...     ...        ...    ...
20153    9. Dharashiv  2022 - 2023            Urad  Summer       2.00   0.53
20154    9. Dharashiv  2022 - 2023           Wheat    Rabi   33447.78   1.55
20155    9. Dharashiv  2022 - 2023  other oilseeds  Kharif     700.20   0.34
20156    9. Dharashiv  2022 - 2023  other oilseeds    Rabi    1536.50   0.33
20157    9. Dharashiv  2022 - 2023  other oilseeds  Summer       6.00   0.44

[20158 rows x 6 columns]

In [52]:
crops=df["crop"].unique()

In [58]:
df["crop"]

0             Arhar/Tur
1                 Bajra
2                  Gram
3                 Jowar
4                 Jowar
              ...
20153              Urad
20154             Wheat
20155    other oilseeds
20156    other oilseeds
20157    other oilseeds
Name: crop, Length: 20158, dtype: str

In [53]:
crops

<StringArray>
[          'Arhar/Tur',               'Bajra',                'Gram',
               'Jowar',               'Maize',   'Moong(Green Gram)',
   'Other Rabi pulses',        'Pulses total',                'Ragi',
                'Rice',           'Sugarcane',     'Total foodgrain',
                'Urad',               'Wheat',         'Castor seed',
        'Cotton(lint)',           'Groundnut',             'Linseed',
          'Niger seed',       'Other Cereals', 'Other Kharif pulses',
   'Rapeseed &Mustard',           'Safflower',             'Sesamum',
            'Soyabean',           'Sunflower',       'Small millets',
      'other oilseeds', 'Other Summer Pulses']
Length: 29, dtype: str

In [61]:
df_encoded

,year,area,yield,district_1. Ahilyanagar,district_10. Dhule,district_11. Gadchiroli,district_12. Gondia,district_13. Hingoli,district_14. Jalgaon,district_15. Jalna,...,crop_Sugarcane,crop_Sunflower,crop_Total foodgrain,crop_Urad,crop_Wheat,crop_other oilseeds,season_Autumn,season_Kharif,season_Rabi,season_Summer
0,1997,17600.00,0.36,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,1997,274100.00,0.56,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,1997,40800.00,0.46,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,1997,900.00,1.22,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,1997,598400.00,0.36,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20153,2022,2.00,0.53,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
20154,2022,33447.78,1.55,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
20155,2022,700.20,0.34,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
20156,2022,1536.50,0.33,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
20157,2022,6.00,0.44,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True

In [62]:
df_encoded_2=pd.get_dummies(df, columns=["district", "season"])

In [64]:
df_encoded_2.columns

Index(['year', 'crop', 'area', 'yield', 'district_1. Ahilyanagar',
       'district_10. Dhule', 'district_11. Gadchiroli', 'district_12. Gondia',
       'district_13. Hingoli', 'district_14. Jalgaon', 'district_15. Jalna',
       'district_16. Kolhapur', 'district_17. Latur', 'district_18. Mumbai',
       'district_19. Mumbai suburban', 'district_2. Akola',
       'district_20. Nagpur', 'district_21. Nanded', 'district_22. Nandurbar',
       'district_23. Nashik', 'district_24. Palghar', 'district_25. Parbhani',
       'district_26. Pune', 'district_27. Raigad', 'district_28. Ratnagiri',
       'district_29. Sangli', 'district_3. Amravati', 'district_30. Satara',
       'district_31. Sindhudurg', 'district_32. Solapur', 'district_33. Thane',
       'district_34. Wardha', 'district_35. Washim', 'district_36. Yavatmal',
       'district_4. Beed', 'district_5. Bhandara', 'district_6. Buldhana',
       'district_7. Chandrapur', 'district_8. Chhatrapati Sambhajinagar',
       'district_9. Dharashiv', 'season_Autumn', 'season_Kharif',
       'season_Rabi', 'season_Summer'],
      dtype='str')

In [69]:
df_encoded_2["year"].dtype

In [70]:
df_encoded_2["year"] = df_encoded_2["year"].str.split(" - ").str[0].astype(int)
df_encoded_2["year"].dtype

dtype('int64')

In [71]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

crop_models = {}
crop_scores = {}

for crop in crops:
    print(f"\nProcessing crop: {crop}")

    #  filter correctly
    df_crop = df_encoded_2[df_encoded_2["crop"] == crop].copy()

    #  correct length check
    if len(df_crop) < 50:
        print(f"Skipped crop-{crop}. Sample too small...\n")
        continue

    # Drop crop column (it’s constant now)
    df_crop = df_crop.drop(columns=["crop"])

    # features + target
    X = df_crop.drop(columns=["yield"])
    y = df_crop["yield"]

    # remove leakage if exists
    X = X.drop(columns=["production"], errors="ignore")

    # split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # model
    rf = RandomForestRegressor(n_estimators=100, random_state=42)
    rf.fit(X_train, y_train)

    # evaluate
    y_pred = rf.predict(X_test)
    r2 = r2_score(y_test, y_pred)

    print(f"R2 Score: {r2}")

    crop_models[crop] = rf
    crop_scores[crop] = r2

Processing crop: Arhar/Tur
R2 Score: 0.39565591095814756

Processing crop: Bajra
R2 Score: 0.6651909336226758

Processing crop: Gram
R2 Score: 0.6359782703867909

Processing crop: Jowar
R2 Score: 0.6708842659310921

Processing crop: Maize
R2 Score: 0.6045598584775986

Processing crop: Moong(Green Gram)
R2 Score: 0.5931692369371357

Processing crop: Other Rabi pulses
R2 Score: 0.18277911422098225

Processing crop: Pulses total
Skipped crop-Pulses total. Sample too small...


Processing crop: Ragi
R2 Score: 0.6409920258050394

Processing crop: Rice
R2 Score: 0.8152299552971135

Processing crop: Sugarcane
Skipped crop-Sugarcane. Sample too small...


Processing crop: Total foodgrain
Skipped crop-Total foodgrain. Sample too small...


Processing crop: Urad
R2 Score: 0.3622584822694481

Processing crop: Wheat
R2 Score: 0.6837900822646739

Processing crop: Castor seed
R2 Score: 0.022082109945702477

Processing crop: Cotton(lint)
R2 Score: 0.08509828130479236

Processing crop: Groundnut
R2 Score: 0.6225352237180448

Processing crop: Linseed
R2 Score: 0.4856396652149002

Processing crop: Niger seed
R2 Score: 0.4351052030335192

Processing crop: Other Cereals
R2 Score: 0.22089867700743515

Processing crop: Other Kharif pulses
R2 Score: 0.2944519429408353

Processing crop: Rapeseed &Mustard
R2 Score: -0.18949942371737682

Processing crop: Safflower
R2 Score: 0.09618841174795234

Processing crop: Sesamum
R2 Score: -0.07250694221452658

Processing crop: Soyabean
R2 Score: 0.43243244317389395

Processing crop: Sunflower
R2 Score: 0.42685338537142115

Processing crop: Small millets
R2 Score: 0.35166161202313084

Processing crop: other oilseeds
R2 Score: 0.10128709506204536

Processing crop: Other Summer Pulses
R2 Score: 0.07428500405966842

In [77]:
print(f"Crop Models:\n{crop_models}\n")
print(f"Crop Scores:\n{crop_scores}\n")

Crop Models:
{'Arhar/Tur': RandomForestRegressor(random_state=42), 'Bajra': RandomForestRegressor(random_state=42), 'Gram': RandomForestRegressor(random_state=42), 'Jowar': RandomForestRegressor(random_state=42), 'Maize': RandomForestRegressor(random_state=42), 'Moong(Green Gram)': RandomForestRegressor(random_state=42), 'Other Rabi pulses': RandomForestRegressor(random_state=42), 'Ragi': RandomForestRegressor(random_state=42), 'Rice': RandomForestRegressor(random_state=42), 'Urad': RandomForestRegressor(random_state=42), 'Wheat': RandomForestRegressor(random_state=42), 'Castor seed': RandomForestRegressor(random_state=42), 'Cotton(lint)': RandomForestRegressor(random_state=42), 'Groundnut': RandomForestRegressor(random_state=42), 'Linseed': RandomForestRegressor(random_state=42), 'Niger seed': RandomForestRegressor(random_state=42), 'Other Cereals': RandomForestRegressor(random_state=42), 'Other Kharif pulses': RandomForestRegressor(random_state=42), 'Rapeseed &Mustard': RandomForestRegressor(random_state=42), 'Safflower': RandomForestRegressor(random_state=42), 'Sesamum': RandomForestRegressor(random_state=42), 'Soyabean': RandomForestRegressor(random_state=42), 'Sunflower': RandomForestRegressor(random_state=42), 'Small millets': RandomForestRegressor(random_state=42), 'other oilseeds': RandomForestRegressor(random_state=42), 'Other Summer Pulses': RandomForestRegressor(random_state=42)}

Crop Scores:
{'Arhar/Tur': 0.39565591095814756, 'Bajra': 0.6651909336226758, 'Gram': 0.6359782703867909, 'Jowar': 0.6708842659310921, 'Maize': 0.6045598584775986, 'Moong(Green Gram)': 0.5931692369371357, 'Other Rabi pulses': 0.18277911422098225, 'Ragi': 0.6409920258050394, 'Rice': 0.8152299552971135, 'Urad': 0.3622584822694481, 'Wheat': 0.6837900822646739, 'Castor seed': 0.022082109945702477, 'Cotton(lint)': 0.08509828130479236, 'Groundnut': 0.6225352237180448, 'Linseed': 0.4856396652149002, 'Niger seed': 0.4351052030335192, 'Other Cereals': 0.22089867700743515, 'Other Kharif pulses': 0.2944519429408353, 'Rapeseed &Mustard': -0.18949942371737682, 'Safflower': 0.09618841174795234, 'Sesamum': -0.07250694221452658, 'Soyabean': 0.43243244317389395, 'Sunflower': 0.42685338537142115, 'Small millets': 0.35166161202313084, 'other oilseeds': 0.10128709506204536, 'Other Summer Pulses': 0.07428500405966842}